window.ccn = [
  'Cowan',
  'Hawkesbury River',
  'Wondabyne',
  'Woy Woy',
  'Koolewong',
  'Tascott',
  'Point Clare',
  'Gosford',
  'Narara',
  'Niagara Park',
  'Lisarow',
  'Ourimbah',
  'Tuggerah',
  'Wyong',
  'Warnervale',
  'Wyee',
  'Morisset',
  'Dora Creek',
  'Awaba',
  'Fassifern',
  'Booragul',
  'Teralba',
  'Cockle Creek',
  'Cardiff',
  'Kotara',
  'Adamstown',
  'Broadmeadow',
  'Hamilton',
  'Newcastle Interchange'
]
window.hun = [
  'Newcastle Interchange',
  'Hamilton',
  'Waratah',
  'Warabrook',
  'Sandgate',
  'Hexham',
  'Tarro',
  'Beresfield',
  'Thornton',
  'Metford',
  'Victoria Street',
  'East Maitland',
  'High Street',
  'Maitland',
  'DUNGOG BRANCH',
  'Telarah',
  'Mindaribba',
  'Paterson',
  'Martins Creek',
  'Hilldale',
  'Wallarobba',
  'Wirragulla',
  'Dungog',
  'SCONE BRANCH',
  'Lochinvar',
  'Greta',
  'Branxton',
  'Singleton',
  'Muswellbrook',
  'Aberdeen',
  'Scone'
]
window.bmt = [
  'Lapstone',
  'Glenbrook',
  'Blaxland',
  'Warrimoo',
  'Valley Heights',
  'Springwood',
  'Faulconbridge',
  'Linden',
  'Woodford',
  'Hazelbrook',
  'Lawson',
  'Bullaburra',
  'Wentworth Falls',
  'Leura',
  'Katoomba',
  'Medlow Bath',
  'Blackheath',
  'Mount Victoria',
  'Bell',
  'Zig Zag',
  'Lithgow',
  'Rydal',
  'Tarana',
  'Bathurst'
]
window.sco = [
  'Helensburgh',
  'Otford',
  'Stanwell Park',
  'Coalcliff',
  'Scarborough',
  'Wombarra',
  'Coledale',
  'Austinmer',
  'Thirroul',
  'Bulli',
  'Woonona',
  'Bellambi',
  'Corrimal',
  'Towradgi',
  'Fairy Meadow',
  'North Wollongong',
  'Wollongong',
  'Coniston',
  'PORT KEMBLA BRANCH',
  'Lysaghts',
  'Cringila',
  'Port Kembla North',
  'Port Kembla',
  'KIAMA BRANCH',
  'Unanderra',
  'Kembla Grange',
  'Dapto',
  'Albion Park',
  'Oak Flats',
  'Shellharbour Junction',
  'Minnamurra',
  'Bombo',
  'Kiama',
  'Gerringong',
  'Berry',
  'Bomaderry'
  ]

window.shl = [
  'Menangle Park',
  'Menangle',
  'Douglas Park',
  'Picton',
  'Tahmoor',
  'Bargo',
  'Yerrinbool',
  'Mittagong',
  'Bowral',
  'Burradoo',
  'Moss Vale',
  'Exeter',
  'Bundanoon',
  'Penrose',
  'Wingello',
  'Tallong',
  'Marulan',
  'Goulburn'
  ]

window.t1 = [
  'Berowra',
  'Mount Kuring-gai',
  'Mount Colah',
  'Asquith',
  'Hornsby',
  'Waitara',
  'Wahroonga',
  'Warrawee',
  'Turramurra',
  'Pymble',
  'Gordon',
  'Killara',
  'Lindfield',
  'Roseville',
  'Chatswood',
  'Artarmon',
  'St Leonards',
  'Wollstonecraft',
  'Waverton',
  'North Sydney',
  'Milsons Point',
  'Wynyard',
  'Town Hall',
  'Central',
  'Redfern',
  'Strathfield',
  'Lidcombe',
  'Auburn',
  'Clyde',
  'Granville',
  'Harris Park',
  'Parramatta',
  'Westmead',
  'Wentworthville',
  'Pendle Hill',
  'Toongabbie',
  'Seven Hills',
  'Blacktown',
  'EMU PLAINS BRANCH',
  'Doonside',
  'Rooty Hill',
  'Mount Druitt',
  'St Marys',
  'Werrington',
  'Kingswood',
  'Penrith',
  'Emu Plains',
  'RICHMOND BRANCH',
  'Marayong',
  'Quakers Hill',
  'Schofields',
  'Riverstone',
  'Vineyard',
  'Mulgrave',
  'Windsor',
  'Clarendon',
  'East Richmond',
  'Richmond '
]

window.t2 = [
  'Museum',
  'St James',
  'Circular Quay',
  'Wynyard',
  'Town Hall',
  'Central',
  'Redfern',
  'Macdonaldtown',
  'Newtown',
  'Stanmore',
  'Petersham',
  'Lewisham',
  'Summer Hill',
  'Ashfield',
  'Croydon',
  'Burwood',
  'Strathfield',
  'Homebush',
  'Flemington',
  'Lidcombe',
  'Auburn',
  'Clyde',
  'Granville',
  'PARAMATTA BRANCH',
  'Harris Park',
  'Paramatta',
  'LEPPINGTON BRANCH',
  'Merrylands',
  'Guildford',
  'Yennora',
  'Fairfield',
  'Canley Vale',
  'Cabramatta',
  'Warwick Farm',
  'Liverpool',
  'Casula',
  'Glenfield',
  'Edmondson Park',
  'Leppington'
]

window.t3 = [
  'Museum',
  'St James',
  'Circular Quay',
  'Wynyard',
  'Town Hall',
  'Central',
  'Redfern',
  'Macdonaldtown',
  'Newtown',
  'Stanmore',
  'Petersham',
  'Lewisham',
  'Summer Hill',
  'Ashfield',
  'Croydon',
  'Burwood',
  'Strathfield',
  'Homebush',
  'Flemington',
  'Lidcombe',
  'Berala',
  'Regents Park',
  'Sefton',
  'Chester Hill',
  'Leightonfield',
  'Villawood',
  'Carramar',
  'Cabramatta',
  'Warwick Farm',
  'Liverpool'
]

window.t4 = [
  'Bondi Junction',
  'Edgecliff',
  'Kings Cross',
  'Martin Place',
  'Town Hall',
  'Central',
  'Redfern',
  'Sydenham',
  'Tempe',
  'Wolli Creek',
  'Arncliffe',
  'Banksia',
  'Rockdale',
  'Kogarah',
  'Carlton',
  'Allawah',
  'Hurstville',
  'Penshurst',
  'Mortdale',
  'Oatley',
  'Como',
  'Jannali',
  'Sutherland',
  'WATERFALL BRANCH',
  'Loftus',
  'Engadine',
  'Heathcote',
  'Waterfall',
  'CRONULLA BRANCH',
  'Kirrawee',
  'Gymea',
  'Miranda',
  'Caringbah',
  'Woolooware',
  'Cronulla'
]

window.t5 = [
  'Richmond',
  'East Richmond',
  'Clarendon',
  'Windsor',
  'Mulgrave',
  'Vineyard',
  'Riverstone',
  'Schofields',
  'Quakers Hill',
  'Marayong',
  'Blacktown',
  'Seven Hills',
  'Toongabbie',
  'Pendle Hill',
  'Wentworthville',
  'Westmead',
  'Parramatta',
  'Harris Park',
  'Merrylands',
  'Guildford',
  'Yennora',
  'Fairfield',
  'Canley Vale',
  'Cabramatta',
  'Warwick Farm',
  'Liverpool',
  'Casula',
  'Glenfield',
  'Edmondson Park',
  'Leppington'
]

window.t6 = [
  'Bankstown',
  'Yagoona',
  'Birrong',
  'Regents Park',
  'Berala',
  'Lidcombe'
]

window.t7 = [
  'Lidcombe',
  'Olympic Park'
]

window.t8 = [
  'Town Hall',
  'Wynyard',
  'Circular Quay',
  'St James',
  'Museum',
  'Central',
  'SYDENHAM BRANCH',
  'Redfern',
  'Erskineville',
  'St Peters',
  'Sydenham',
  'AIRPORT BRANCH',
  'Green Square',
  'Mascot',
  'Domestic Airport',
  'International Airport',
  'Wolli Creek',
  'BRANCHES REJOIN',
  'Turrella',
  'Bardwell Park',
  'Bexley North',
  'Kingsgrove',
  'Beverly Hills',
  'Narwee',
  'Riverwood',
  'Padstow',
  'Revesby',
  'Panania',
  'East Hills',
  'Holsworthy',
  'Glenfield',
  'Macquarie Fields',
  'Ingleburn',
  'Minto',
  'Leumeah',
  'Campbelltown',
  'Macarthur'
]

window.t9 = [
  'Gordon',
  'Killara',
  'Lindfield',
  'Roseville',
  'Chatswood',
  'Artarmon',
  'St Leonards',
  'Wollstonecraft',
  'Waverton',
  'North Sydney',
  'Milsons Point',
  'Wynyard',
  'Town Hall',
  'Central',
  'Redfern',
  'Burwood',
  'Strathfield',
  'North Strathfield',
  'Concord West',
  'Rhodes',
  'Meadowbank',
  'West Ryde',
  'Denistone',
  'Eastwood',
  'Epping',
  'Cheltenham',
  'Beecroft',
  'Pennant Hills',
  'Thornleigh',
  'Normanhurst',
  'Hornsby '
]

window.m1 = [
  'Tallawong',
  'Rouse Hill',
  'Kellyville',
  'Bella Vista',
  'Norwest',
  'Hills Showground',
  'Castle Hill',
  'Cherrybrook',
  'Epping',
  'Macquarie University',
  'Macquarie Park',
  'North Ryde',
  'Chatswood',
  'Crows Nest',
  'Victoria Cross',
  'Sydney Harbour',
  'Barangaroo',
  'Martin Place',
  'Gadigal',
  'Central',
  'Waterloo',
  'Sydenham'
]
