window.ccn = [
  'Cowan Station',
  'Hawkesbury River Station',
  'Wondabyne Station',
  'Woy Woy Station',
  'Koolewong Station',
  'Tascott Station',
  'Point Clare Station',
  'Gosford Station',
  'Narara Station',
  'Niagara Park Station',
  'Lisarow Station',
  'Ourimbah Station',
  'Tuggerah Station',
  'Wyong Station',
  'Warnervale Station',
  'Wyee Station',
  'Morisset Station',
  'Dora Creek Station',
  'Awaba Station',
  'Fassifern Station',
  'Booragul Station',
  'Teralba Station',
  'Cockle Creek Station',
  'Cardiff Station',
  'Kotara Station',
  'Adamstown Station',
  'Broadmeadow Station',
  'Hamilton Station',
  'Newcastle Interchange Station'
]
window.hun = [
  'Newcastle Interchange Station',
  'Hamilton Station',
  'Waratah Station',
  'Warabrook Station',
  'Sandgate Station',
  'Hexham Station',
  'Tarro Station',
  'Beresfield Station',
  'Thornton Station',
  'Metford Station',
  'Victoria Street Station',
  'East Maitland Station',
  'High Street Station',
  'Maitland Station',
  '',
  'DUNGOG BRANCH',
  '',
  'Telarah Station',
  'Mindaribba Station',
  'Paterson Station',
  'Martins Creek Station',
  'Hilldale Station',
  'Wallarobba Station',
  'Wirragulla Station',
  'Dungog Station',
  '',
  'SCONE BRANCH',
  '',
  'Lochinvar Station',
  'Greta Station',
  'Branxton Station',
  'Singleton Station',
  'Muswellbrook Station',
  'Aberdeen Station',
  'Scone Station'
]
window.bmt = [
  'Lapstone Station',
  'Glenbrook Station',
  'Blaxland Station',
  'Warrimoo Station',
  'Valley Heights Station',
  'Springwood Station',
  'Faulconbridge Station',
  'Linden Station',
  'Woodford Station',
  'Hazelbrook Station',
  'Lawson Station',
  'Bullaburra Station',
  'Wentworth Falls Station',
  'Leura Station',
  'Katoomba Station',
  'Medlow Bath Station',
  'Blackheath Station',
  'Mount Victoria Station',
  'Bell Station',
  'Zig Zag Station',
  'Lithgow Station',
  'Rydal Station',
  'Tarana Station',
  'Bathurst Station'
]
window.sco = [
  'Helensburgh Station',
  'Otford Station',
  'Stanwell Park Station',
  'Coalcliff Station',
  'Scarborough Station',
  'Wombarra Station',
  'Coledale Station',
  'Austinmer Station',
  'Thirroul Station',
  'Bulli Station',
  'Woonona Station',
  'Bellambi Station',
  'Corrimal Station',
  'Towradgi Station',
  'Fairy Meadow Station',
  'North Wollongong Station',
  'Wollongong Station',
  'Coniston Station',
  '',
  'PORT KEMBLA BRANCH',
  '',
  'Lysaghts Station',
  'Cringila Station',
  'Port Kembla North Station',
  'Port Kembla Station',
  '',
  'KIAMA BRANCH',
  '',
  'Unanderra Station',
  'Kembla Grange Station',
  'Dapto Station',
  'Albion Park Station',
  'Oak Flats Station',
  'Shellharbour Junction Station',
  'Minnamurra Station',
  'Bombo Station',
  'Kiama Station',
  'Gerringong Station',
  'Berry Station',
  'Bomaderry Station'
  ]

window.shl = [
  'Menangle Park Station',
  'Menangle Station',
  'Douglas Park Station',
  'Picton Station',
  'Tahmoor Station',
  'Bargo Station',
  'Yerrinbool Station',
  'Mittagong Station',
  'Bowral Station',
  'Burradoo Station',
  'Moss Vale Station',
  'Exeter Station',
  'Bundanoon Station',
  'Penrose Station',
  'Wingello Station',
  'Tallong Station',
  'Marulan Station',
  'Goulburn Station'
  ]

window.t1 = [
  'Berowra Station',
  'Mount Kuring-gai Station',
  'Mount Colah Station',
  'Asquith Station',
  'Hornsby Station',
  'Waitara Station',
  'Wahroonga Station',
  'Warrawee Station',
  'Turramurra Station',
  'Pymble Station',
  'Gordon Station',
  'Killara Station',
  'Lindfield Station',
  'Roseville Station',
  'Chatswood Station',
  'Artarmon Station',
  'St Leonards Station',
  'Wollstonecraft Station',
  'Waverton Station',
  'North Sydney Station',
  'Milsons Point Station',
  'Wynyard Station',
  'Town Hall Station',
  'Central Station',
  'Redfern Station',
  'Strathfield Station',
  'Lidcombe Station',
  'Auburn Station',
  'Clyde Station',
  'Granville Station',
  'Harris Park Station',
  'Parramatta Station',
  'Westmead Station',
  'Wentworthville Station',
  'Pendle Hill Station',
  'Toongabbie Station',
  'Seven Hills Station',
  'Blacktown Station',
  '',
  'EMU PLAINS BRANCH',
  '',
  'Doonside Station',
  'Rooty Hill Station',
  'Mount Druitt Station',
  'St Marys Station',
  'Werrington Station',
  'Kingswood Station',
  'Penrith Station',
  'Emu Plains Station',
  '',
  'RICHMOND BRANCH',
  '',
  'Marayong Station',
  'Quakers Hill Station',
  'Schofields Station',
  'Riverstone Station',
  'Vineyard Station',
  'Mulgrave Station',
  'Windsor Station',
  'Clarendon Station',
  'East Richmond Station',
  'Richmond Station'
]

window.t2 = [
  'Museum Station',
  'St James Station',
  'Circular Quay Station',
  'Wynyard Station',
  'Town Hall Station',
  'Central Station',
  'Redfern Station',
  'Macdonaldtown Station',
  'Newtown Station',
  'Stanmore Station',
  'Petersham Station',
  'Lewisham Station',
  'Summer Hill Station',
  'Ashfield Station',
  'Croydon Station',
  'Burwood Station',
  'Strathfield Station',
  'Homebush Station',
  'Flemington Station',
  'Lidcombe Station',
  'Auburn Station',
  'Clyde Station',
  'Granville Station',
  '',
  'PARAMATTA BRANCH',
  '',
  'Harris Park Station',
  'Paramatta Station',
  '',
  'LEPPINGTON BRANCH',
  '',
  'Merrylands Station',
  'Guildford Station',
  'Yennora Station',
  'Fairfield Station',
  'Canley Vale Station',
  'Cabramatta Station',
  'Warwick Farm Station',
  'Liverpool Station',
  'Casula Station',
  'Glenfield Station',
  'Edmondson Park Station',
  'Leppington Station'
]

window.t3 = [
  'Museum Station',
  'St James Station',
  'Circular Quay Station',
  'Wynyard Station',
  'Town Hall Station',
  'Central Station',
  'Redfern Station',
  'Macdonaldtown Station',
  'Newtown Station',
  'Stanmore Station',
  'Petersham Station',
  'Lewisham Station',
  'Summer Hill Station',
  'Ashfield Station',
  'Croydon Station',
  'Burwood Station',
  'Strathfield Station',
  'Homebush Station',
  'Flemington Station',
  'Lidcombe Station',
  'Berala Station',
  'Regents Park Station',
  'Sefton Station',
  'Chester Hill Station',
  'Leightonfield Station',
  'Villawood Station',
  'Carramar Station',
  'Cabramatta Station',
  'Warwick Farm Station',
  'Liverpool Station'
]

window.t4 = [
  'Bondi Junction Station',
  'Edgecliff Station',
  'Kings Cross Station',
  'Martin Place Station',
  'Town Hall Station',
  'Central Station',
  'Redfern Station',
  'Sydenham Station',
  'Tempe Station',
  'Wolli Creek Station',
  'Arncliffe Station',
  'Banksia Station',
  'Rockdale Station',
  'Kogarah Station',
  'Carlton Station',
  'Allawah Station',
  'Hurstville Station',
  'Penshurst Station',
  'Mortdale Station',
  'Oatley Station',
  'Como Station',
  'Jannali Station',
  'Sutherland Station',
  '',
  'WATERFALL BRANCH',
  '',
  'Loftus Station',
  'Engadine Station',
  'Heathcote Station',
  'Waterfall Station',
  '',
  'CRONULLA BRANCH',
  '',
  'Kirrawee Station',
  'Gymea Station',
  'Miranda Station',
  'Caringbah Station',
  'Woolooware Station',
  'Cronulla Station'
]

window.t5 = [
  'Richmond Station',
  'East Richmond Station',
  'Clarendon Station',
  'Windsor Station',
  'Mulgrave Station',
  'Vineyard Station',
  'Riverstone Station',
  'Schofields Station',
  'Quakers Hill Station',
  'Marayong Station',
  'Blacktown Station',
  'Seven Hills Station',
  'Toongabbie Station',
  'Pendle Hill Station',
  'Wentworthville Station',
  'Westmead Station',
  'Parramatta Station',
  'Harris Park Station',
  'Merrylands Station',
  'Guildford Station',
  'Yennora Station',
  'Fairfield Station',
  'Canley Vale Station',
  'Cabramatta Station',
  'Warwick Farm Station',
  'Liverpool Station',
  'Casula Station',
  'Glenfield Station',
  'Edmondson Park Station',
  'Leppington Station'
]

window.t6 = [
  'Bankstown Station',
  'Yagoona Station',
  'Birrong Station',
  'Regents Park Station',
  'Berala Station',
  'Lidcombe Station'
]

window.t7 = [
  'Lidcombe Station',
  'Olympic Park Station'
]

window.t8 = [
  'Town Hall Station',
  'Wynyard Station',
  'Circular Quay Station',
  'St James Station',
  'Museum Station',
  'Central Station',
  '',
  'SYDENHAM BRANCH',
  '',
  'Redfern Station',
  'Erskineville Station',
  'St Peters Station',
  'Sydenham Station',
  '',
  'AIRPORT BRANCH',
  '',
  'Green Square Station',
  'Mascot Station',
  'Domestic Airport Station',
  'International Airport Station',
  'Wolli Creek Station',
  '',
  'BRANCHES REJOIN',
  '',
  'Turrella Station',
  'Bardwell Park Station',
  'Bexley North Station',
  'Kingsgrove Station',
  'Beverly Hills Station',
  'Narwee Station',
  'Riverwood Station',
  'Padstow Station',
  'Revesby Station',
  'Panania Station',
  'East Hills Station',
  'Holsworthy Station',
  'Glenfield Station',
  'Macquarie Fields Station',
  'Ingleburn Station',
  'Minto Station',
  'Leumeah Station',
  'Campbelltown Station',
  'Macarthur Station'
]

window.t9 = [
  'Gordon Station',
  'Killara Station',
  'Lindfield Station',
  'Roseville Station',
  'Chatswood Station',
  'Artarmon Station',
  'St Leonards Station',
  'Wollstonecraft Station',
  'Waverton Station',
  'North Sydney Station',
  'Milsons Point Station',
  'Wynyard Station',
  'Town Hall Station',
  'Central Station',
  'Redfern Station',
  'Burwood Station',
  'Strathfield Station',
  'North Strathfield Station',
  'Concord West Station',
  'Rhodes Station',
  'Meadowbank Station',
  'West Ryde Station',
  'Denistone Station',
  'Eastwood Station',
  'Epping Station',
  'Cheltenham Station',
  'Beecroft Station',
  'Pennant Hills Station',
  'Thornleigh Station',
  'Normanhurst Station',
  'Hornsby Station'
]

window.m1 = [
  'Tallawong Station',
  'Rouse Hill Station',
  'Kellyville Station',
  'Bella Vista Station',
  'Norwest Station',
  'Hills Showground Station',
  'Castle Hill Station',
  'Cherrybrook Station',
  'Epping Station',
  'Macquarie University Station',
  'Macquarie Park Station',
  'North Ryde Station',
  'Chatswood Station',
  'Crows Nest Station',
  'Victoria Cross Station',
  'Sydney Harbour Station',
  'Barangaroo Station',
  'Martin Place Station',
  'Gadigal Station',
  'Central Station',
  'Waterloo Station',
  'Sydenham Station'
]
